ALTER TYPE "ContactEventType" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_AUTOMATION_QUEUED';
ALTER TYPE "ContactEventType" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_SENT_AUTOMATION';
ALTER TYPE "ContactEventType" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_SEND_FAILED';
ALTER TYPE "ContactEventType" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_SEQUENCE_COMPLETED';

ALTER TABLE "ContactHistory"
ADD COLUMN "source" TEXT,
ADD COLUMN "provider" TEXT,
ADD COLUMN "messageId" TEXT,
ADD COLUMN "sentAt" TIMESTAMP(3);

CREATE INDEX "ContactHistory_type_idx" ON "ContactHistory"("type");
CREATE INDEX "ContactHistory_sentAt_idx" ON "ContactHistory"("sentAt");
